In [9]:
import pandas as pd
brics = pd.read_csv("/content/brics.csv", index_col = 0)
print(brics)

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [10]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [12]:
brics["area"] > 8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [15]:
is_huge = brics["area"] > 8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [16]:
brics[brics["area"] > 8]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [31]:
import pandas as pd
cars = pd.read_csv("/content/cars.csv", index_col = 0)

dr = cars["drives_right"]
cars[dr]

sel = cars["drives_right"]==True
cars[sel]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [20]:
cars[cars["drives_right"]==True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [32]:
cars[cars["cars_per_cap"] < 100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

In [33]:
offset = 10
while offset  != 0:
  offset = offset - 1
  print(offset)

9
8
7
6
5
4
3
2
1
0

In [90]:
import random as rd
sorte = 100
numero = 0
while numero != sorte:
  numero = rd.randint(0,100)
  print(numero)

73
1
33
62
41
31
93
60
17
28
38
0
68
44
78
57
31
48
36
70
60
58
6
76
7
69
93
65
11
2
27
60
86
39
65
3
21
28
87
71
27
34
68
73
60
15
93
74
55
70
6
95
76
90
35
92
56
19
71
42
65
12
22
6
3
79
0
2
23
59
71
23
86
99
8
77
19
64
86
37
6
54
26
67
65
31
80
41
88
71
5
27
63
28
69
82
29
2
76
80
22
34
28
70
29
12
68
55
85
38
1
48
6
52
2
35
100